In [1]:
import pandas as pd
df=pd.read_csv("traffic_data.csv")
df.head()

day  hour                area        lat        lon  current_speed  \
0    2    12       Diwan Cheruvu  17.046290  81.843918             30   
1    2    12  Morumpudi Junction  16.996048  81.801988             33   
2    2    12            VL Puram  17.000361  81.794579             36   
3    2    12    Bommuru Junction  16.970026  81.798208             53   
4    2    12        Lala Cheruvu  17.025931  81.806299             53   

   free_flow_speed traffic_level  temperature  code  windspeed  
0               30           Low         30.8     2        8.2  
1               33           Low         31.1     2        7.9  
2               36           Low         31.1     2        7.9  
3               53           Low         31.1     2        7.9  
4               53           Low         30.9     2        7.9

In [2]:
X=df.drop(["area","traffic_level","current_speed","free_flow_speed","temperature","code","windspeed"],axis=1)
y=df["traffic_level"]

In [3]:
X.values

array([[ 2.        , 12.        , 17.04629017, 81.84391764],
       [ 2.        , 12.        , 16.99604829, 81.80198795],
       [ 2.        , 12.        , 17.00036112, 81.79457901],
       ...,
       [ 6.        , 14.        , 16.99251444, 82.21067511],
       [ 6.        , 14.        , 16.96469875, 82.22472639],
       [ 6.        , 14.        , 17.01400687, 82.28410307]])

In [4]:
locations= {
    "diwan cheruvu": [17.04629016871151, 81.84391764161728],
    "morumpudi junction": [16.996048288046573, 81.80198795480973],
    "vl puram": [17.000361116740542, 81.79457900941965],
    "bommuru junction": [16.970026044376908, 81.7982077898937],
    "lala cheruvu": [17.02593120555252, 81.80629901087161],
    "pushkar ghat cir": [17.006969029272703, 81.767905981993721],
    "azad chowk": [17.006653914430878, 81.77629003487216],
    "devi chowk circle": [17.00979647101888, 81.77610012750917],
    "balajipeta junction": [16.97671457656731, 81.79384356744096],
    "kesavaram railway gate": [16.93112749732291, 81.88170907194181],
    "giet nh": [17.059489892275263, 81.869371840258811],
    "delta hospital nh": [17.011499419423277, 81.80917916023519],
    "gsl nh": [17.067684063534045, 81.88328358025326],
    "jn road nh": [17.008003289850134, 81.80995996296429],
    "rtc cs mall": [17.000363703893182, 81.78944972209622],
    "old bypass road": [17.005045820972253, 81.7801544865445],
    "jampeta": [17.00493586307353, 81.780213297543],
    "syamalamba temple rd": [16.999305680527787, 81.77559463029415],
    "stadium rd": [16.996918736129484, 81.7777554114391],
    "anala venkata apparao road": [17.007811731690097, 81.7921873982832],
    "manasa hospital": [17.007717340321364, 81.78586393475791],
    "apex hospital": [17.006938634443195, 81.79054340970453],
    "nandamgani raju junction": [17.009486970902955, 81.77954016677567],
    "y juncton": [17.012826235294103, 81.78265351880752],
    "chiranjeevi bus stand": [17.014572541382044, 81.77861516264718],
    "gokavaram bus stand": [17.00967984828635, 81.77120172225537],
    "devichowk to mochi veedhi": [17.00897558377485, 81.77516315124535],
    "jandapanja road": [17.005793945788838, 81.77361261386221],
    "cmr mall": [17.006285650143596, 81.77066111476915],
    "markandeya swamy temple road": [17.002419348927187, 81.76737485108524],
    "kathreru road": [17.021766650089877, 81.77483965237695],
    "tirumala college road": [17.04317118735671, 81.77557759223698],
    "dhavaleswaram main road": [16.95028007716461, 81.78232137122522],
    "church center bypass": [17.004904032408977, 81.78017113264912],
    "central jail road": [17.0183461072747, 81.79134447760869],
    "brothern church": [17.02347300450597, 81.78349635298017],
    "quary market": [17.032306965496208, 81.78809778066346],
    "airport road": [17.04178820195048, 81.79431781829038],
    "rial cum road bridge": [16.99704707573163, 81.76927353762291],
    "main road": [16.999891585565052, 81.77174995367827],
    "bhanu gudi": [16.970727621131044, 82.23604297660549],
    "vankata narayana railway gate": [16.973097407997937, 82.22603037626632],
    "munsif gari junction": [16.937053050836603, 82.23297479867091],
    "apt college road": [16.92997583523028, 82.23448294817929],
    "dairyfarm centre": [16.956302106919356, 82.24871504989581],
    "gaati center": [16.93563418662961, 82.22835108063681],
    "nagamalli thota centre": [16.986766105909542, 82.24004443228684],
    "temple street": [16.94692319878384, 82.2319585390418],
    "main road (2)": [16.9477758788922, 82.23388897523365],
    "sarpavaram junction": [16.994895450984338, 82.24274883366579],
    "pr clg road": [16.95806544175642, 82.23109820773215],
    "bala cheruvu": [16.95281937073767, 82.2323379008641],
    "nukalamma temple": [16.96300884823827, 82.23441835065452],
    "cinema road": [16.94826208774934, 82.23632529143106],
    "beach road": [17.008947642214952, 82.28321349284704],
    "glass house centre": [16.948718637695816, 82.23396555251772],
    "gold market centre": [16.946806476806653, 82.23381228730807],
    "masjid centre": [16.951018411377465, 82.2340447518843],
    "fire office road": [16.95625954468796, 82.23319640172481],
    "district court": [16.957505554489668, 82.22707180043267],
    "ggh": [16.9551649315784, 82.23011317679611],
    "kokila centre": [16.95965297508154, 82.22372616365254],
    "drivers colony": [16.9195687218521, 82.23867107250433],
    "rto office": [16.975555403090365, 82.24875195678766],
    "vakalapudi junction": [17.006117793712892, 82.26343084127797],
    "indrapalem bridge": [16.95965297508154, 82.22372616365254],
    "revenue office": [16.953915323179874, 82.23158617323973],
    "bus stand": [16.968628884485902, 82.2396254653395],
    "jntuk road": [16.9733394966521, 82.23687898351096],
    "kalpana centre": [16.95614085026494, 82.23667031643537],
    "jagannadhapuram bridge": [16.94224348809935, 82.23327482540806],
    "kakinada anchorage port": [16.93999009392696, 82.25623410490785],
    "karnam gari junction": [16.977303001042785, 82.22772653959622],
    "pitapuram kakinada road": [17.001239678156328, 82.24517313922694],
    "pitapuram kakinada highway": [17.05454405203872, 82.25091475318834],
    "achampeta junction": [17.022515117068984, 82.24885404796437],
    "satya gowri theatre road": [16.9448962699546, 82.23602478600985],
    "madhavapatam centre": [16.99251444215439, 82.2106751103578],
    "gandhi circle": [16.96469875062046, 82.22472639247694],
    "light house": [17.014006865277864, 82.28410306612057]
}

In [5]:
locations['diwan cheruvu'][0]

17.04629016871151

In [6]:
from sklearn.linear_model import LogisticRegression
lgr=LogisticRegression(max_iter=1000)
lgr

LogisticRegression(max_iter=1000)

In [7]:
targets={"Low":0,
        "Medium":1,
        "High":2}

In [8]:
y=y.map(targets)

In [9]:
y[0]

np.int64(0)

In [10]:
lgr.fit(X,y)

LogisticRegression(max_iter=1000)

In [11]:
X.columns

Index(['day', 'hour', 'lat', 'lon'], dtype='object')

In [12]:
num_to_cat={0:"Low",
        1:"Medium",
           2:"High"}

In [13]:
import requests
location='diwan cheruvu'
day=2
time=12
lat=locations[location][0]
lon=locations[location][1]
url2= ("https://api.open-meteo.com/v1/forecast"f"?latitude={lat}&longitude={lon}&current_weather=true")
response2=requests.get(url2)
w_data=response2.json()
temp=w_data["current_weather"]["temperature"]
pred=lgr.predict([[day,time,lat,lon]])
pred
print(f"traffic on that day might be {num_to_cat[int(pred)]} and the todays temperature at that location is {temp}")

traffic on that day might be Low and the todays temperature at that location is 33.5


C:\Users\vamsi\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\base.py:493: UserWarning: X does not have valid feature names, but LogisticRegression was fitted with feature names
  warnings.warn(
C:\Users\vamsi\AppData\Local\Temp\ipykernel_24556\1110516248.py:13: DeprecationWarning: Conversion of an array with ndim > 0 to a scalar is deprecated, and will error in future. Ensure you extract a single element from your array before performing this operation. (Deprecated NumPy 1.25.)
  print(f"traffic on that day might be {num_to_cat[int(pred)]} and the todays temperature at that location is {temp}")


In [22]:
preds=lgr.predict(X)

In [31]:
import numpy as np
y.values

array([0, 0, 0, ..., 0, 0, 0])

In [32]:
preds

array([0, 0, 0, ..., 0, 0, 0])

In [44]:
lgr.score(X,y)

0.6822916666666666

In [51]:
from sklearn.tree import DecisionTreeClassifier
dtc=DecisionTreeClassifier(min_samples_split=3)
dtc

DecisionTreeClassifier(min_samples_split=3)

In [52]:
dtc.fit(X,y)

DecisionTreeClassifier(min_samples_split=3)

In [53]:
dtc.score(X,y)

0.9614583333333333